# docker-compose.yaml file specifically for the doh-client
# see https://github.com/m13253/dns-over-https for upstream
# source

version: '2.2'

services:
  doh-client:     #DOH Client for local network
    container_name: SageCreek-DOH-Client
    image: buckaroogeek/doh-client:latest
    hostname: dohclient
    domainname: lan
    mac_address: d0:ca:ab:cd:ef:03
    cap_add:
      - NET_ADMIN
    networks:
      macvlan1:
        ipv4_address: 192.168.110.203
    command: ["-conf=/etc/dns-over-https/doh-client.conf",
              "-verbose=false"]  # override default config
    volumes:
      - /volume1/docker/dohclient:/etc/dns-over-https  #location for config
    ports:
      - 53/tcp
      - 53/udp
      - 5380/tcp
    restart: unless-stopped

networks:
  macvlan1:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.110.0/24            # <-- Update
          gateway: 192.168.110.1              # <-- Update
          ip_range: 192.168.110.192/26        # <-- Update
          aux_addresses:
            -host: 192.168.110.193            # <-- Reserve, Update

