#! /bin/bash

# simple script that uses buildah multiarch build and then pushs resulting image
# to docker hub
# need to buildah login first

# REMINDER! - Update DTAG before running script!
DTAG="2.2.15"

buildah bud --platform linux/amd64,linux/arm64 --manifest doh-client:$DTAG ./Dockerfile.client

buildah manifest push --all doh-client:$DTAG docker://buckaroogeek/doh-client:$DTAG
